# ed25519_select_supported_impl works as a priority queue, it will return first known and supported library from ARGN
function(ed25519_select_supported_impl SELECTED)
  if(DEFINED ${SELECTED})
    if(NOT TARGET ${${SELECTED}})
      message(FATAL_ERROR "Selected implementation ${${SELECTED}} of ${SELECTED} is not supported in current configuration.")
    endif()
  else()
    foreach(lib ${ARGN})
      if (TARGET ${lib})
        message(STATUS "Automatically selected implementation ${lib} for ${SELECTED}.")
        set(${SELECTED} ${lib} PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endif()
endfunction()
